---
version: '3'
services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:5.3.1
    ports:
      - "12181:12181"
    network_mode: host
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 172.17.0.1:12888:13888;172.17.0.1:22888:23888;172.17.0.1:32888:33888
  zoo:
    image: zhenik/nomad-zoo:3.5.5
    build: .
    ports:
    - 8080
    volumes:
    - "./v/zoo.cfg:/conf/zoo.cfg"
    - "./v/zoo.cfg.dynamic:/conf/zoo.cfg.dynamic"
